apiVersion: v1
kind: Service
metadata:
   name: kubernetes-dashboard
   namespace: kubernetes-dashboard
   annotations:
   labels:
     k8s-app: kubernetes-dashboard
 spec:
   ports:
   - port: 80
     protocol: TCP
     targetPort: 8443
   selector:
     k8s-app: kubernetes-dashboard
   type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard-ingress-path
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - "dev.ahyeha.com"
      secretName: apps-tls
  rules:
    - host: "dev.ahyeha.com"
      http:
        paths:
          - path: /kubernetes-dashboard(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 80
