apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2
  namespace: dev-ahyeha
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 50Gi
  hostPath:
    path: /mysql2
